#!/bin/bash
# Stolen from : https://github.com/Grafikart/dotfiles

tell() {
  printf "\033[1;33m|-- ${*}\033[0m\n"
  printf "\033[0;31m" 1>&2 ;
  $* || {
    printf "\033[0m"
  }
}

explain() {
  printf "\033[1;34m${1}\033[0m\n"
}

success() {
  printf "\033[1;32m${1}\033[0m\n"
}

error() {
  printf "\033[1;31m${1}\033[0m\n"
}

install_cmd(){

  PACKAGE_NAME=$@

  YUM_CMD=$(which yum)
  APT_GET_CMD=$(which apt-get)
  BREW_CMD=$(which brew)
  ARCH_CMD=$(which pacman)

  # add your own package

  #TEMPLATE=$(which template)

  if [ ! -z $YUM_CMD ]; then
    sudo yum install $PACKAGE_NAME

  elif [ ! -z $APT_GET_CMD ]; then
    sudo apt-get install $PACKAGE_NAME

  elif [ ! -z $BREW_CMD ]; then
    sudo brew install $PACKAGE_NAME

  elif [ ! -z $ARCH_CMD ]; then
    sudo pacman -S install $PACKAGE_NAME

  else

    printf "\033[0;31m" 1>&2 ;
    printf "Error can't install package $PACKAGE_NAME"
    printf "\033[0m"
    printf "No package manager found"
    printf "please add yours to $HOME/dotfiles/install/inc/functions"
    exit 1;
  fi
}
