#!/usr/bin/env bash


BASEDIR="$(dirname "$0")"
. "$BASEDIR/inc/functions"

"$BASEDIR/git"
"$BASEDIR/python"
"$BASEDIR/node"
"$BASEDIR/pinentry-tty"
"$BASEDIR/rbw"
"$HOME/dotfiles/bin/rbw" unlock
"$BASEDIR/tssh"
"$BASEDIR/tmux"
"$BASEDIR/neovim"
"$BASEDIR/zsh"
"$BASEDIR/dotfiles"
