#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

wget -q https://github.com/atom/atom/releases/latest -O /tmp/latest
explain "Download ATOM text editor"
  wget --progress=bar -q 'https://github.com'$(cat /tmp/latest | grep -o -E 'href="([^"#]+)atom-amd64.deb"' | cut -d'"' -f2 | sort | uniq) -O /tmp/atom-amd64.deb -q --show-progress

explain "Install ATOM text editor"
  tell sudo dpkg -i /tmp/atom-amd64.deb
  tell apm install advanced-open-file
  tell apm install auto-indent
  tell apm install autocomplete-paths
  tell apm install color-picker
  tell apm install emmet
  tell apm install file-icons
  tell apm install foldername-tabs
  tell apm install language-lua
  tell apm install merge-conflicts
  tell apm install minimap
  tell apm install remote-atom
  tell apm install flat-ui-syntax
  tell apm install pdf-view
  tell apm install markdown-themeable-pdf
