#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

ignoreRC="README.md|.gitmodules|.gitignore|screenshot.png|compton.conf|LICENSE|dircolors|riot.txt"
dir=~/dotfiles

explain "Create symlink for dotfiles"
# change to the dotfiles directory
cd $dir

files=`find . -maxdepth 1 -type f | sed 's|./||' | egrep -v $ignoreRC`

# create symlinks from the homedir to any files in the ~/dotfiles directory specified
for file in $files; do
    rm ~/.$file
    tell ln -s $dir/$file ~/.$file
done
zsh
