#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

mkdir -p ~/lab/ || true

ignoreRC="README.md|.gitignore|screenshot.png|LICENSE.md|dircolors|riot.txt|.notags|vimium|package.list|package_all.list|logouser.txt|settings_dataGrip.jar|LSP_settings.json|urlview|settings_idea.jar|keyd.conf"
dir=~/dotfiles


explain "Create symlink for files config"
mkdir ~/.config/nvim
explain "Symlink nvim config"
\rm -rf ~/.config/nvim 2> /dev/null || true
tell ln -sf ~/dotfiles/nvim ~/.config/nvim
explain "Symlink other configs"
[ -d ~/.config/ ] || mkdir ~/.config/
tell cp -f --recursive --symbolic-link $dir/config/* ~/.config

explain "Create symlink for dotfiles"
# change to the dotfiles directory
cd $dir

files=`find . -maxdepth 1 -type f | sed 's|./||' | egrep -v $ignoreRC`

# create symlinks from the homedir to any files in the ~/dotfiles directory specified
for file in $files; do
  if [ -f ~/.$file ]; then
    tell rm ~/.$file
  fi
  tell ln -s $dir/$file ~/.$file
done

# if [ -d ~/.var/app/org.geeqie.Geeqie/ ]; then
#   \rm -rf ~/.var/app/org.geeqie.Geeqie/config/geeqie
#   mkdir -p ~/.var/app/org.geeqie.Geeqie/config/geeqie
#   tell cp -f --recursive --symbolic-link $dir/config/geeqie/* ~/.var/app/org.geeqie.Geeqie/config/geeqie
#   flatpak override --user --filesystem=/usr/bin/exiftool org.geeqie.Geeqie
# fi



explain "RipGrep Install"
cd /tmp
curl -LO 'https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-x86_64-unknown-linux-musl.tar.gz'
tar xf ripgrep-*.tar.gz
yes | cp ripgrep-*/rg $HOME/dotfiles/bin/rg
rm ripgrep-*.tar.gz
cd -


explain "FD Install"
cd /tmp
wget -O fd.tar.gz "https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz"
mkdir -p fd
tar xf fd.tar.gz -C fd --strip-components=1
ls fd
cp ./fd/fd ~/dotfiles/bin/fd
rm fd.tar.gz
rm -rf ./fd

if [ ! -d ~/.fzf ]; then
  explain "FZF Install"
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all
fi

explain "Atuin Install"
curl --proto '=https' --tlsv1.2 -LsSf https://github.com/atuinsh/atuin/releases/download/v18.4.0/atuin-installer.sh | sh

explain "SSH Install"
mkdir -p ~/.ssh/sockets/
if ! grep -q "AddKeysToAgent yes" ~/.ssh/config; then
  explain "Conf ssh config"
  touch "$HOME"/.ssh/config
  chmod +w "$HOME"/.ssh/config
  cat <<EOF >>"$HOME"/.ssh/config
Host *
  AddKeysToAgent yes
  ForwardAgent yes

  GSSAPIAuthentication no

  ControlMaster auto
  ControlPath ~/.ssh/sockets/%r@%h-%p
  ControlPersist 600

  IPQoS throughput
EOF
chmod 600 "$HOME"/.ssh/config
fi

explain "RBW Install"
$HOME/dotfiles/bin/rbw unlocked 2> /dev/null > /dev/null
if [[ $? -eq 0 ]]; then
  ~/.atuin/bin/atuin login \
    -u $($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'username') \
    -p $($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'password') \
    -k "$($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'key')"
else
 echo "" > $HOME/dotfiles/zsh/priv.zsh
fi

# Custom Completion Scripts
mkdir -p ~/.oh-my-zsh/custom/completions

~/.atuin/bin/atuin gen-completions --shell zsh > ~/.oh-my-zsh/custom/completions/_atuin
$HOME/dotfiles/bin/rbw_bin/rbw gen-completions zsh > ~/.oh-my-zsh/custom/completions/_rbw


# switch this remote git from http to ssh if needed
url=$(git remote get-url origin)
ssh_url="${url#https://github.com/}"

if [[ "$ssh_url" != "$url" ]]; then
    # Remove trailing slash if any
    ssh_url="${ssh_url%/}"
    # Build SSH URL
    ssh_url="git@github.com:${ssh_url}.git"

    echo "Switching remote from $url to $ssh_url"
    git remote set-url origin "$ssh_url"
    git config pull.rebase false # small config
fi

success "Success"
