#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

mkdir -p ~/lab/ || true

ignoreRC="README.md|.gitignore|screenshot.png|LICENSE.md|dircolors|riot.txt|.notags|vimium|package.list|package_all.list|logouser.txt|settings_dataGrip.jar|LSP_settings.json|urlview|settings_idea.jar"
dir=~/dotfiles

explain "Create symlink for dotfiles"
# change to the dotfiles directory
cd $dir

files=`find . -maxdepth 1 -type f | sed 's|./||' | egrep -v $ignoreRC`

# create symlinks from the homedir to any files in the ~/dotfiles directory specified
for file in $files; do
  if [ -f ~/.$file ]; then
    tell rm ~/.$file
  fi
  tell ln -s $dir/$file ~/.$file
done

explain "Create symlink for files config"
mkdir ~/.config/nvim
[ -d ~/.config/ ] || mkdir ~/.config/
tell cp -f --recursive --symbolic-link $dir/config/* ~/.config
# tell cp -f --recursive --symbolic-link $dir/vim/* ~/.vim/

explain "Symlink nvim to vim"
tell ln -sf ~/.vim ~/.config/nvim
tell ln -sf ~/.vimrc ~/.config/nvim/init.vim


if [ ! -d ~/.fzf ]; then
  explain "FZF Install"
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install --all
fi

if [ ! -f ~/dotfiles/bin/bw ]; then
  explain "Bitwarden-cli Install"
  VERSION="1.22.1"
  TAR="bw-linux-${VERSION}.zip"
  DOWNLOAD_URL="https://github.com/bitwarden/cli/releases/download/v${VERSION}/${TAR}"
  wget -O /tmp/$TAR "${DOWNLOAD_URL}"
  unzip -d ~/dotfiles/bin /tmp/$TAR
  chmod +x ~/dotfiles/bin/bw
  rm /tmp/$TAR
fi


if [ ! -f ~/.cache/imgcat_install ]; then
  explain "Imgcat install"
  home=$(pwd)
  cd /tmp
  git clone https://github.com/wookayin/python-imgcat
  cd python-imgcat
  pip install -e .
  cd $home
  touch ~/.cache/imgcat_install
fi

success "Success"
