#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Install latest git version (without https support).."
cd /tmp
# \rm -rf git 2> /dev/null || true
# git clone https://github.com/git/git --depth=1 || exit
cd git

export NO_OPENSSL=1
export NO_CURL=1
export CFLAGS="${CFLAGS} -static"

run_with_spinner "make configure; ./configure --prefix=$HOME/.local"
run_with_spinner make -j $(nproc)
run_with_spinner "make install; make clean"
rm $HOME/.local/bin/ngit 2> /dev/null || true
mv $HOME/.local/bin/git $HOME/.local/bin/ngit

success "[GIT] Success"
