#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

success "[Github APP] Start"

install_github_app pinentry "pchampio/build-static-pinentry" "https.*pinentry.*stripped.gz$" &
install_github_app tmux "pchampio/build-static-tmux" "https.*tmux.*amd64.*stripped.gz$" &
install_github_app difft "Wilfred/difftastic" "https.*difft.*x86_64.*musl.*gz$" &
install_github_app diff-so-fancy "so-fancy/diff-so-fancy" "https.*diff-so-fancy$" &
install_github_app gotty "yudai/gotty" "https.*gotty.*linux.*amd64.*.gz" &
install_github_app fd "sharkdp/fd" "https.*fd.*x86_64.*musl.*gz$" &
install_github_app rg "BurntSushi/ripgrep" "https.*ripgrep.*x86_64.*musl.*gz$" &
install_github_app atuin "atuinsh/atuin" "https.*atuin.*x86_64.*linux-musl.*gz$" &
install_github_app "rbw,rbw-agent" "doy/rbw" "https.*rbw.*linux.*amd64.*gz$" &
install_github_app fzf "junegunn/fzf" "https.*fzf.*linux.*amd64.*gz$" &
install_github_app tssh "trzsz/trzsz-ssh" "https.*tssh.*linux_x86.*gz$" &
install_github_app tsshd "trzsz/tsshd" "https.*tsshd.*linux_x86.*gz$" &
install_github_app "trzsz,trz,tsz" "trzsz/trzsz-go" "https.*trzsz.*linux_x86.*gz$" &
install_github_app "tree-sitter-cli" "tree-sitter/tree-sitter" "https.*tree-sitter.*linux-x64.*gz$" &

wait

# Post download steps
cd $HOME/.local/bin
ln -s tree-sitter-cli tree-sitter # Expected name is tree-sitter (no -cli)

success "[Github APP] Success"
