#!/usr/bin/env bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Install java"

run_with_spinner "echo y | ~/.local/share/junest/bin/junest -f -- sudo yay -S jre-openjdk"
if [[ ! $? -eq 0 ]]; then
  error "[JAVA] Error"
  exit
fi

success "[JAVA] Success"
