#!/bin/bash


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

[ -d ~/.local/share/junest ] && {
  read -p "Delete older junest? [y] " -n 1 -r
  echo ""    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    tell rm -rf ~/.local/share/junest ~/.junest
  fi
}

[ ! -f ~/.local/share/junest/bin/junest ] && {
  explain "Installation junest"
  git clone https://github.com/fsquillace/junest.git ~/.local/share/junest
  run_with_spinner ~/.local/share/junest/bin/junest setup
} 

explain "MAJ pacman"
run_with_spinner ~/.local/share/junest/bin/junest -f -- pacman -Syyu --noconfirm
run_with_spinner ~/.local/share/junest/bin/junest -f -- pacman -S --needed git base-devel --noconfirm
