#!/bin/bash


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation de keyd (Need sudo)"

cd /tmp
rm -rf keyd || true
git clone https://github.com/rvaiya/keyd --depth=1
cd keyd
make
sudo make uninstall || true
sudo make install
sudo systemctl enable keyd && sudo systemctl start keyd

sudo rm /etc/keyd/german.conf || true
sudo rm /etc/keyd/all.conf || true

# tell sudo ln -s "$HOME/dotfiles/keyd/german.conf" /etc/keyd/german.conf # disable german qwerty conf by default
tell sudo ln -s "$HOME/dotfiles/config/keyd/all.conf" /etc/keyd/all.conf
tell sudo keyd reload

explain "XkbOptions compose:menu for unicode éèà"
# similar as: setxkbmap -option compose:menu
sudo bash -c 'cat <<EOF >> /etc/X11/xorg.conf.d/compose.conf
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbOptions" "compose:menu"
EndSection
EOF'

explain "Depending on your desktop environment, there might be a GUI configuration option available to you. For instance, I have read one report that Ubuntu has a setting in "System → Preferences → Keyboard → Layouts → Options" to specify it. In KDE, it is "Settings → Input Devices → Keyboard → Advanced → Position of Compose key." I don't have personal experience with those, though. This applies to systems running Wayland, too; the https://www.reddit.com/r/linux/comments/17xll20/the_compose_key_and_why_you_should_enable_it/ discussion for this article has some good info. "

explain "Set compose key to: 'Menu key'!!!!!"

success "[KEYD] Success"
