#!/usr/bin/env bash

# Stable
# NVIM_RELEASE_URL=https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-linux-x86_64.tar.gz
# Nightly
NVIM_RELEASE_URL=https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

success "[NVIM] Start"
explain "Setup neovim plugins"

I_TITLE="Downloading nvim" run_with_spinner "curl -sS -L $NVIM_RELEASE_URL | tar -C $HOME/.local/bin -xz"
[ -f "$HOME/.local/bin/nvim" ] && rm "$HOME/.local/bin/nvim"
ln -s "$HOME/.local/bin/nvim-linux-x86_64/bin/nvim" "$HOME/.local/bin/nvim"

if [ ! -e ~/.config/nvim/spell ]; then
  mkdir -p ~/.config/nvim/spell
  cd ~/.config/nvim/spell
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.spl
fi

# [ -d  "$HOME/.local/share/nvim/lazy/" ] && rm -rf "$HOME/.local/share/nvim/lazy/"
[ -d  "$HOME/.local/share/nvim/lazier/" ] && rm -rf "$HOME/.local/share/nvim/lazier/"
I_TITLE="[Nvim] Lazy install" run_with_spinner "$HOME/.local/bin/zsh -ic '
command ssh -T git@prr.re && nvim --headless -c \"lua local lazypath = vim.fn.stdpath(\\\"data\\\") .. \\\"/lazier/lazier.nvim\\\"; if not vim.loop.fs_stat(lazypath) then vim.fn.system({\\\"git\\\",\\\"clone\\\",\\\"--filter=blob:none\\\",\\\"https://github.com/jake-stewart/lazier.nvim.git\\\",\\\"--branch=main\\\", lazypath}) end; vim.opt.rtp:prepend(lazypath); require(\\\"lazy\\\").install()\" -c \"qa\"
'"

I_TITLE="[Tools] Opencode" run_with_spinner "PATH=$HOME/.opencode/bin:$PATH curl -fsSL https://opencode.ai/install | bash"
# remove crap from zshrc (added by opencode install)
apply_sed_to_dotfiles '/^# opencode$/,+1d'


success "[NVIM] Success"
