#!/usr/bin/env bash


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Download latest nvim"
cd /tmp
run_with_spinner "curl -L https://github.com/neovim/neovim-releases/releases/download/nightly/nvim-linux-x86_64.tar.gz | tar -C $HOME/dotfiles/bin -xz"

if [ ! -e ~/.config/nvim/spell ]; then
  explain "Spelling dictionary"
  mkdir -p ~/.config/nvim/spell
  cd ~/.config/nvim/spell
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.spl
fi

success "[NVIM] Success"
