#!/usr/bin/env bash


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Download latest nvim"
cd /tmp
run_with_spinner "curl -sS -L https://github.com/neovim/neovim-releases/releases/download/nightly/nvim-linux-x86_64.tar.gz | tar -C $HOME/.local/bin -xz"
[ -f "$HOME/.local/bin/nvim" ] && rm "$HOME/.local/bin/nvim"
ln -s "$HOME/.local/bin/nvim-linux-x86_64/bin/nvim" "$HOME/.local/bin/nvim"

if [ ! -e ~/.config/nvim/spell ]; then
  explain "Spelling dictionary"
  mkdir -p ~/.config/nvim/spell
  cd ~/.config/nvim/spell
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.latin1.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.spl
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/fr.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.sug
  run_with_spinner wget https://ftp.nluug.nl/vim/runtime/spell/en.utf-8.spl
fi

[ ! -d ~/.ssh/ ] && mkdir -p ~/.ssh/
# add some known_hosts for later neovim package manager git clone.
ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null
# manualy add my self hosted server
echo '|1|lRIfMUrVckQFC94Srhr/xCshUbM=|2ce5rmYGTY9LRXkru3gQ0IhlYVc= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrxfg+PBcrQUqf9AQ76ZQP3rD3x9w6lH3eQQOCbwd08' >> ~/.ssh/known_hosts

success "[NVIM] Success"
