#!/usr/bin/env sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

if [ ! -d "${HOME}/.zinit/bin" ];
then
  explain "Install zinit"
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin;
fi

# Install nix
if [ ! -d "/nix" ]; then
  explain "Install nix"
  sudo mkdir /nix
  sudo chown "$USER" /nix
  sh <(curl -L https://nixos.org/nix/install) --no-daemon
fi
source "$HOME/.nix-profile/etc/profile.d/nix.sh"

mkdir -p ${HOME}/.config/home-manager

if ! [ -x "$(command -v home-manager)" ]; then
  explain "Install nix home-manager"
  nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
  nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
  nix-channel --update

  nix-shell '<home-manager>' -A install
fi


if [ ! -f ~/.config/nix/nix.conf ]; then
  touch ~/.config/nix/nix.conf
  echo 'experimental-features = nix-command flakes' > ~/.config/nix/nix.conf
fi

explain "Create symlink for home.nix and includes"
rm -rf ${HOME}/.config/home-manager/*
mkdir -p ${HOME}/.config/home-manager/includes
tell cp -f --recursive --symbolic-link `pwd`/$BASEDIR/../nix/includes/* ${HOME}/.config/home-manager/includes
tell ln -sf `pwd`/$BASEDIR/../nix/user.nix ${HOME}/.config/home-manager/home.nix

nix-channel --update

cd $BASEDIR/../nix
tell home-manager switch --flake '.'

# export XDG_DATA_DIRS="$HOME/.nix-profile/share/:$XDG_DATA_DIRS"
# sudo update-desktop-database

explain "Run:  source ~/.nix-profile/etc/profile.d/nix.sh"
