#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

cd $(dirname $0)


explain "Install node with nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
source ~/.nvm/nvm.sh
nvm install node

success "Success"
