#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

cd $(dirname $0)

success "[NODE] Start"

# Remove dotfiles bins to avoid loop with my own define node/npm
export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v "^$HOME/dotfiles/bin\$" | paste -sd ':' -)

explain "Install node with nvm"
[ -d "$HOME/.nvm" ] && rm -rf "$HOME/.nvm"
run_with_spinner "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash"

# Remove NVM_DIR export lines
apply_sed_to_dotfiles '/^export NVM_DIR=.*/d'
# Remove lines starting with [.*NVM_DIR
apply_sed_to_dotfiles '/^\[.*NVM_DIR/d'


run_with_spinner "source ~/.nvm/nvm.sh; nvm install node"
echo "    Node info: $(~/dotfiles/bin/node --version)"

success "[NODE] Success"
