#!/bin/bash


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

success "[ASK] Start"

groups=$(id -nG)

# Check if the user is in 'sudo' (Debian/Ubuntu) or 'wheel' (RedHat/Fedora) group
if echo "$groups" | grep -qw "sudo" || echo "$groups" | grep -qw "wheel"; then
  read -p "[SUDO chsh] Change shell to set zsh ? [y] " -n 1 -r
  echo ""    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "$wherezsh" | sudo tee -a /etc/shells
    sudo chsh -s "$wherezsh"  "${USER}"
    success "[ASK] End"
    exit 0
  fi
fi

# OR
## Fake chsh by adding executing zsh in other shells

wherezsh="$HOME/.local/bin/zsh"

target_file=$(get_config_for_current_shell)

# zsh is already the default
if [[ "$target_file" =~ \.zshrc$ ]]; then
  success "[ASK] End"
  exit 0
fi

# Determine proper exec line based on shell type
if [[ "$target_file" =~ \.cshrc$|\.login$|\.tcshrc$ ]]; then
    exec_line="if ( -f $wherezsh ) exec $wherezsh -l"
else
    exec_line="[ -f $wherezsh ] && [ \"\${JUNEST_ENV}\" != \"1\" ] && exec $wherezsh -l"
fi

# Prompt user
read -p "[FAKE chsh] Add exec '$wherezsh' to $target_file ? [y] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    [[ ! -f "$target_file" ]] && touch "$target_file"
    echo "$exec_line" >> "$target_file"
    echo "Updated $target_file"
fi

success "[ASK] End"
