#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation of rbw"


APP_name=rbw # bin name
APP=rbw_bin # dir name
SITE="doy/rbw" # github link

# CREATE DIRECTORIES
[ -d "$HOME/dotfiles/bin/$APP" ] && rm -rf "$HOME/dotfiles/bin/$APP"
[ -n "$APP" ] && mkdir -p "$HOME/dotfiles/bin/$APP/tmp" && cd "$HOME/dotfiles/bin/$APP/tmp" || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -sS -Ls https://api.github.com/repos/$SITE/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP_name.*linux.*amd64.*gz$" | head -1)
wget -q --show-progress "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version

success "[RBW] Success"
