#!/usr/bin/env bash

set -o errexit

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions


explain "Instalation de rust bitwarden"
yes 1 | ~/.local/share/junest/bin/junest -- yay -S rbw-git || true
yes | ~/.local/share/junest/bin/junest -- yay -S rbw-git
yes | ~/.local/share/junest/bin/junest -- yay -S sshpass
yes | ~/.local/share/junest/bin/junest -- yay -S openssh

