#!/usr/bin/env bash

set -o errexit

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions


explain "Instalation de deps"
# yes 1 | ~/.local/share/junest/bin/junest -- yay -S rbw-git || true
# yes | ~/.local/share/junest/bin/junest -- yay -S rbw-git
yes | ~/.local/share/junest/bin/junest -- yay -S --noconfirm sshpass
yes | ~/.local/share/junest/bin/junest -- yay -S --noconfirm openssh
yes | ~/.local/share/junest/bin/junest -- yay -S --noconfirm rust

explain "Instalation de rust bitwarden"
\rm -rf /tmp/rbw-git-pkg || true
mkdir /tmp/rbw-git-pkg || true
cd /tmp/rbw-git-pkg
cat <<EOF >> PKGBUILD
# Maintainer: Jesse Luehrs <archlinux@tozt.net>
pkgname=rbw-git
_name=\${pkgname%-*}
pkgver=1.3.0
pkgrel=2
makedepends=('rust' 'cargo' 'git')
depends=('pinentry')
conflicts=('rbw' 'rbw-bin')
provides=('rbw')
arch=('i686' 'x86_64' 'aarch64')
source=()
sha256sums=()
pkgdesc="unofficial bitwarden cli"
license=('MIT')

build() {
    # git clone https://git.tozt.net/\${_name}
    git clone https://github.com/doy/rbw \${_name}
    cd "\${_name}"
    rm Cargo.lock
    curl https://raw.githubusercontent.com/doy/rbw/bdf255d8efca18feed9dbe99d6166012821b8768/Cargo.lock > Cargo.lock
    rm Cargo.toml
    curl https://raw.githubusercontent.com/doy/rbw/bdf255d8efca18feed9dbe99d6166012821b8768/Cargo.toml > Cargo.toml
    sed -i '68i rustix = { version = "0.38.28", features = ["termios", "procfs", "process", "pipe"] }' Cargo.toml
    sed -i '68i regex = "1.10.2"' Cargo.toml
    cargo build --release
    cargo run --release --locked --bin rbw -- gen-completions bash >bash-completions
    cargo run --release --locked --bin rbw -- gen-completions zsh >zsh-completions
    cargo run --release --locked --bin rbw -- gen-completions fish >fish-completions
}

check() {
    cd "\${_name}"
    cargo test --release --locked
}

package() {
    cd "\${_name}"
    install -Dm 755 target/release/rbw -t "\${pkgdir}/usr/bin"
    install -Dm 755 target/release/rbw-agent -t "\${pkgdir}/usr/bin"
    install -Dm 644 LICENSE -t "\${pkgdir}/usr/share/licenses/\${pkgname}"
    install -Dm 644 bash-completions "\${pkgdir}/usr/share/bash-completion/completions/rbw"
    install -Dm 644 zsh-completions "\${pkgdir}/usr/share/zsh/site-functions/_rbw"
    install -Dm 644 fish-completions "\${pkgdir}/usr/share/fish/vendor_completions.d/rbw.fish"
}
EOF
yes | ~/.local/share/junest/bin/junest -- makepkg -Acsi
