#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions


explain "Installation de Remote ATOM"
  tell sudo curl -o /usr/local/bin/rmate https://raw.githubusercontent.com/aurora/rmate/master/rmate
  sudo chmod +x /usr/local/bin/rmate
  mv /usr/local/bin/rmate /usr/local/bin/ratom
  explain "--> ssh -R 52698:localhost:52698 user@example.com"
  explain "---> rmate test.txt"
