#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

success "[SECRETS] Start"

"$HOME/.local/bin/zsh" -ic "$HOME/dotfiles/bin/rbw unlock; ssh" && success "[RBW] Unlocked"

explain "Setup atuin secrets"
$dir/bin/rbw unlocked 2> /dev/null > /dev/null
if [[ $? -eq 0 ]]; then
  ~/.local/bin/atuin login \
    -u $($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'username') \
    -p $($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'password') \
    -k "$($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'key')" 2> /dev/null > /dev/null
fi

explain "Setup SSH secrets"
# add some known_hosts for later neovim package manager git clone.
I_TITLE="[SSH] add github.com/prr.re to known_hosts" run_with_spinner "ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null"
# manualy add my self hosted server, ssh-keyscan doesn't work (because of our custom infra)
echo '|1|lRIfMUrVckQFC94Srhr/xCshUbM=|2ce5rmYGTY9LRXkru3gQ0IhlYVc= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrxfg+PBcrQUqf9AQ76ZQP3rD3x9w6lH3eQQOCbwd08' >> ~/.ssh/known_hosts
"$HOME/.local/bin/zsh" -ic "ssh -T git@prr.re" 2>/dev/null >/dev/null

success "[SECRETS] Success"
