#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

success "[SECRETS] Start"

"$HOME/.local/bin/zsh" -ic "$HOME/dotfiles/bin/rbw unlock" && success "[RBW] Unlocked"

explain "Setup atuin secrets"
$HOME/dotfiles/bin/rbw unlocked 2> /dev/null > /dev/null
if [[ $? -eq 0 ]]; then
  ~/.local/bin/atuin login \
    -u "$($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'username')" \
    -p "$($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'password')" \
    -k "$($HOME/dotfiles/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'key')" 2> /dev/null > /dev/null
fi

explain "Setup SSH secrets"
# add some known_hosts for later neovim package manager git clone.
I_TITLE="[SSH] add github.com/prr.re to known_hosts" run_with_spinner "ssh-keyscan github.com >> ~/.ssh/known_hosts 2> /dev/null"
# manualy add my self hosted server, ssh-keyscan doesn't work (because of our custom infra)
echo '|1|lRIfMUrVckQFC94Srhr/xCshUbM=|2ce5rmYGTY9LRXkru3gQ0IhlYVc= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrxfg+PBcrQUqf9AQ76ZQP3rD3x9w6lH3eQQOCbwd08' >> ~/.ssh/known_hosts

success "[SECRETS] Success"
