#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Setup secrets"
$dir/bin/rbw unlocked 2> /dev/null > /dev/null
if [[ $? -eq 0 ]]; then
  ~/.local/bin/atuin login \
    -u $($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'username') \
    -p $($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'password') \
    -k "$($dir/bin/rbw get '29feee89-3717-4aa2-8278-362f02e3e10e' --field 'key')" 2> /dev/null > /dev/null
fi

success "[DOTFILES] Success"
