#!/bin/bash

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation of tssh"

APP=tssh
SITE="trzsz/trzsz-ssh"

# CREATE DIRECTORIES
[ -n "$APP" ] && mkdir -p "$HOME/dotfiles/bin/$APP/tmp" "$HOME/dotfiles/bin/$APP/icons" && cd "$HOME/dotfiles/bin/$APP/tmp" || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -sS -Ls https://api.github.com/repos/$SITE/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP.*linux_x86.*gz$" | head -1)
wget -q --show-progress "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1


if ! grep -q "PromptThemeLayout" "$HOME/.tssh.conf" 2>/dev/null; then
    echo 'PromptThemeLayout = tiny' >> "$HOME/.tssh.conf"
fi


explain "Installation of tsshd"

APP=tsshd
SITE="trzsz/tsshd"

# CREATE DIRECTORIES
[ -n "$APP" ] && mkdir -p "$HOME/dotfiles/bin/$APP/tmp" "$HOME/dotfiles/bin/$APP/icons" && cd "$HOME/dotfiles/bin/$APP/tmp" || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -sS -Ls https://api.github.com/repos/$SITE/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP.*linux_x86.*gz$" | head -1)
wget -q --show-progress "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1


explain "Installation of trzsz"

APP=trzsz
SITE="trzsz/trzsz-go"

# CREATE DIRECTORIES
[ -n "$APP" ] && mkdir -p "$HOME/dotfiles/bin/$APP/tmp" "$HOME/dotfiles/bin/$APP/icons" && cd "$HOME/dotfiles/bin/$APP/tmp" || exit 1

# DOWNLOAD AND PREPARE THE APP, $version is also used for updates
version=$(curl -sS -Ls https://api.github.com/repos/$SITE/releases | sed 's/[()",{} ]/\n/g' | grep -oi "https.*$APP.*linux_x86.*gz$" | head -1)
wget -q --show-progress "$version" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
cd ..
if [ -d ./tmp/* 2>/dev/null ]; then mv ./tmp/*/* ./; else mv ./tmp/* ./"$APP" 2>/dev/null || mv ./tmp/* ./; fi
rm -R -f ./tmp || exit 1
echo "$version" > ./version
chmod a+x ./"$APP" || exit 1

success "[TSSH] Success"
