#!/bin/sh


BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions
dir=~/dotfiles


curl --version 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  echo "Could not find curl."
  exit 1
fi

wget --version 2>&1 > /dev/null
if [ $? -ne 0 ]; then
  echo "Could not find wget"
  exit 1
fi


explain "Download Vim-plug (Vim plugins manager)"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [ ! -e  ~/.vim/gutentags ]; then
  mkdir -p ~/.vim/gutentags
fi
if [ ! -e $HOME/.vim/spell ]; then
  explain "Spelling dictionary"
  mkdir -p ~/.vim/spell
  cd ~/.vim/spell
  wget http://ftp.vim.org/vim/runtime/spell/fr.latin1.spl
  wget http://ftp.vim.org/vim/runtime/spell/fr.latin1.sug
  wget http://ftp.vim.org/vim/runtime/spell/fr.utf-8.spl
  wget http://ftp.vim.org/vim/runtime/spell/fr.utf-8.sug
  wget http://ftp.vim.org/vim/runtime/spell/en.utf-8.sug
  wget http://ftp.vim.org/vim/runtime/spell/en.utf-8.spl
fi

mkdir -p ~/.vim
mkdir -p ~/.config
mkdir -p ~/.config/nvim

tell ln -sf ~/.vimrc ~/.config/nvim/init.vim
tell cp -f --recursive --symbolic-link $dir/vim/* ~/.vim/

explain "Symlink nvim to vim"
tell ln -sf ~/.vim/* ~/.config/nvim
tell ln -sf ~/.vimrc ~/.config/nvim/init.vim

mkdir -p ~/.vimundo

python3 -m pip install --user --upgrade pynvim

explain "Vim plugins"
$HOME/dotfiles/bin/nvim +UpdateRemotePlugins +qa

$HOME/dotfiles/bin/nvim +PlugInstall +qa

explain "RipGrep"
cd /tmp
curl -LO 'https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-x86_64-unknown-linux-musl.tar.gz'
tar xf ripgrep-*.tar.gz
cp ripgrep-*/rg $HOME/dotfiles/bin/rg
rm ripgrep-*.tar.gz
cd -
