#!/usr/bin/env bash

set -o errexit

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

yes | ~/.local/share/junest/bin/junest -f -- pacman -S gvim # for the X11* deps


\rm -rf /tmp/wezterm-pkg || true
mkdir /tmp/wezterm-pkg || true
cd /tmp/wezterm-pkg
cat <<EOF >> PKGBUILD

pkgname=("wezterm-git")
pkgdesc="A terminal emulator implemented in Rust, using OpenGL ES 2 for rendering."
pkgver=20230421.075330.e0a92c73
pkgrel=1
arch=("x86_64" "i686")
url="https://github.com/wez/wezterm"
license=("MIT")
depends=(
  "dbus"
  "fontconfig"
  "hicolor-icon-theme"
  "libx11"
  "libxkbcommon-x11"
  "wayland"
  "xcb-util-image"
  "xcb-util-keysyms"
  "xcb-util-wm"
)
makedepends=("cargo" "cmake" "git" "pkgconf" "python")
provides=("wezterm" "wezterm-gui" "wezterm-mux-server")
conflicts=("wezterm" "wezterm-bin" "wezterm-nightly-bin")
source=()
sha256sums=()

prepare() {
  cd "\$srcdir"
  git clone https://github.com/wez/wezterm.git --depth=1
  git clone https://github.com/harfbuzz/harfbuzz.git
  git clone https://github.com/glennrp/libpng.git
  git clone https://github.com/madler/zlib.git
  git clone https://github.com/wez/freetype2.git
  cd "\$srcdir/wezterm"
  git submodule init
  git config "submodule.harfbuzz/harfbuzz.url" "\$srcdir/harfbuzz"
  git config "submodule.freetype/libpng.url" "\$srcdir/libpng"
  git config "submodule.deps/freetype/zlib.url" "\$srcdir/zlib"
  git config "submodule.freetype2.url" "\$srcdir/freetype2"
  git -c protocol.file.allow=always submodule update
  cargo fetch --locked --target "\$CARCH-unknown-linux-gnu"
}

pkgver() {
  cd "\$srcdir/wezterm" || exit 1
  git -c "core.abbrev=8" show -s "--format=%cd-%h" "--date=format:%Y%m%d-%H%M%S" | tr - .
}

build() {
  cd "\$srcdir/wezterm" || exit 1
  bash ci/check-rust-version.sh
  cargo build --release --target \$CARCH-unknown-linux-gnu --features vendored-fonts
  tic -x -o "\$srcdir/terminfo" "\$srcdir/wezterm/termwiz/data/wezterm.terminfo"
}

package() {
  cd "\$srcdir/wezterm" || exit 1

  install -Dsm755 target/release/wezterm "\$pkgdir/usr/bin/wezterm"
  install -Dsm755 target/release/wezterm-gui "\$pkgdir/usr/bin/wezterm-gui"
  install -Dsm755 target/release/wezterm-mux-server "\$pkgdir/usr/bin/wezterm-mux-server"
  install -Dsm755 target/release/strip-ansi-escapes "\$pkgdir/usr/bin/strip-ansi-escapes"

  install -Dm644 assets/icon/terminal.png "\$pkgdir/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png"
  install -Dm644 assets/wezterm.desktop "\$pkgdir/usr/share/applications/org.wezfurlong.wezterm.desktop"
  install -Dm644 assets/wezterm.appdata.xml "\$pkgdir/usr/share/metainfo/org.wezfurlong.wezterm.appdata.xml"
  install -Dm644 assets/wezterm-nautilus.py "\$pkgdir/usr/share/nautilus-python/extensions/wezterm-nautilus.py"
  install -Dm644 ../terminfo/w/wezterm "\$pkgdir/usr/share/terminfo/w/wezterm"

  install -Dm644 assets/shell-integration/wezterm.sh "\$pkgdir/etc/profile.d/wezterm.sh"
  install -Dm644 assets/shell-completion/bash "\$pkgdir/usr/share/bash-completion/completions/wezterm"
  install -Dm644 assets/shell-completion/zsh "\$pkgdir/usr/share/zsh/site-functions/_wezterm"
  install -Dm644 assets/shell-completion/fish "\$pkgdir/usr/share/fish/completions/wezterm.fish"

  install -Dm644 LICENSE.md -t "\${pkgdir}/usr/share/licenses/\${pkgname}"
}

EOF
~/.local/share/junest/bin/junest -- makepkg -Acsi
yes | cp ~/.junest/bin/wezterm ~/dotfiles/bin/wezterm

# cat <<EOF >> ${HOME}/.local/share/applications/wezterm-git-junest.desktop
# [Desktop Entry]                                                                                                                                                                           
# Name=WezTerm-Git                                                                                                                                                                              
# Comment=Wez's Terminal Emulator Junest                                                                                                                                                           
# Keywords=shell;prompt;command;commandline;cmd;                                                                                                                                            
# Icon=org.wezfurlong.wezterm                                                                                                                                                               
# StartupWMClass=org.wezfurlong.wezterm                                                                                                                                                     
# TryExec=wezterm                                                                                                                                                                           
# Exec=wezterm start --cwd .                                                                                                                                                                
# Type=Application                                                                                                                                                                          
# Categories=System;TerminalEmulator;Utility;                                                                                                                                               
# Terminal=false
# EOF

success "Success"
