#!/bin/sh

BASEDIR=$(dirname $0)
. $BASEDIR/inc/functions

explain "Installation de gnome-font-viewer"
  tell sudo apt-get install gnome-font-viewer

explain "Installation d'arc-theme"
  tell wget http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_15.10/Release.key
  sudo apt-key add - < Release.key
  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/arc-theme.list"
  tell sudo apt-get update
  tell sudo apt-get install arc-theme

explain "Installation de flat icons"grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
  tell sudo add-apt-repository ppa:noobslab/icons
  tell sudo apt-get update
  tell sudo apt-get install ultra-flat-icons

explain "Installation du theme pour le terminal"
  tell cp $BASEDIR/files/terminalrc ~/.config/xfce4/terminal/terminalrc

explain "Désactivation du Alt+Clic"
  tell xfconf-query -c xfwm4 -p /general/easy_click -s none

explain "Installation du gestionnaire du moniteur système"
  tell sudo apt-get install gnome-system-monitor
  tell sudo apt-get install htop

explain "Mise en place de la configuration personnalisée"
  cp $BASEDIR/files/xfce4-keyboard-shortcuts.xml $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
  cp $BASEDIR/files/xfce4-panel.xml $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/

explain "Indicator plugins taskbar"
  sudo add-apt-repository ppa:nilarimogard/webupd8
  sudo apt-get update
  tell sudo apt-get install indicator-netspeed

  sudo apt-get install python3-psutil, curl git
  tell git clone https://github.com/fossfreedom/indicator-sysmonitor.git
  cd indicator-sysmonitor
  tell sudo make install
  explain "add indicator-netspeed & to /etc/rc.local"
