alias cls="clear && ls"
alias gs="git status"
alias gau="git add -u"
# alias e="thunar &> /dev/null &"
alias e="thunarCmd > /dev/null 2>&1"
alias tmux="TERM=screen-256color-bce tmux "
alias x=extract  #Function extract
alias q="exit"
alias dc="docker-compose"
alias wifi="killall nm-applet; nm-applet > /dev/null 2>&1 &; disown"
alias stfu="amixer -c 0 cset 'numid=10' 1"
alias zup3x="~/lab/python/zup3x/zup3x.py -kl 'qwerty' -u CHAMPI16 -p 80948"
alias size="du -h . --max-depth=1"
alias http_serv="python2 -m SimpleHTTPServer "
alias doc="/bin/d"
alias sshuttle="sshuttle --dns -vvr drakirus@drakirus.xyz 0/0"
alias STFU="pulseaudio -k && sudo alsa force-reload"
alias paclean="sudo pacman -Rns \$(pacman -Qqtd)"
alias backup="rsync -avPh --cvs-exclude --exclude-from="$HOME/.rsync.excludes" ~/lab /run/mount/NAS/xps13-Backup/"
alias nas="sudo mkdir -p /run/mount/NAS; sudo mount -t nfs -rw 192.168.16.134:/volume1/Share /run/mount/NAS/"
alias unas="sudo umount -l /run/mount/NAS"
# alias cp="rsync -ah --partial --inplace --info=progress2"
alias tri="exiftool -if '\$rating >= 1' -d './tri' '-directory<createdate' ."
alias bt="sudo systemctl start bluetooth.service"
alias neof="neofetch --memory_display barinfo"
alias grip="grip --pass afab9ab158c3a52283f9bf2adfc2b6a3fe6286b2"
alias weeb_send="rsync -vPh ~/Weeb/* drakirus@drakirus.xyz:APP/data/www/gif"
alias resume_send="test -f ~/Téléchargements/resume.pdf && mv ~/Téléchargements/resume.pdf ~/lab/resume/resume.pdf; rsync -vPh ~/lab/resume/resume.pdf drakirus@drakirus.xyz:APP/data/www/resume"
alias drak="ssh drakirus@drakirus.xyz"
alias mv="mv -iv"
alias cp="cp -aiv"
alias py="python"
alias py2="python2"
alias docker_alpine="docker run -it --rm alpine /bin/ash"
alias music="mpv . --shuffle"
alias df="df --type=ext4 -h"
alias ptjson='python -m json.tool'
alias mip="curl --silent ifconfig.co/json | prettyjson"
alias de="adb devices"
alias co="cordova"
alias rm='trash'

alias lowwifi='sudo iwconfig wlan0 txpower 15'
